window.CONSTANTS = {
  FALLING_AMMO: 'AMMO',
  FALLING_HEALTH: 'HEALTH',
  FALLING_ENEMY: 'ENEMY',
  FALLING_ENEMY_COLOR: 'black',
  FALLING_ENEMY_STROKE: '#110952',
  FALLING_DEFAULT_STROKE: '#110952',
  FALLING_AMMO_COLOR: '#ebef00',
  FALLING_HEALTH_COLOR: '#10b910',
  PLAYER_COLOR: '#FF7F66',
}